src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: UserRepository::class)]
/**
 * @ORM\Entity
 * @UniqueEntity("mail",
 *     message="L'adresse mail est déjà utilisé.")
 */

class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'string', length: 100)]
    private $firstname;


    #[ORM\Column(type: 'string', length: 100, unique: true)]
    private $mail;

    #[ORM\Column(type: 'string', length: 10)]
    private $code;

    #[ORM\Column(type: 'string', length: 10)]
    private $codeActivated;

    #[ORM\Column(type: 'datetime')]
    private $creationTime;

    #[ORM\Column(type: 'string', length: 100)]
    private $Gain;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getCodeActivated(): ?string
    {
        return $this->codeActivated;
    }

    public function setCodeActivated(string $codeActivated): self
    {
        $this->codeActivated = $codeActivated;

        return $this;
    }

    public function getCreationTime(): ?\DateTimeInterface
    {
        return $this->creationTime;
    }

    public function setCreationTime(\DateTimeInterface $creationTime): self
    {
        $this->creationTime = $creationTime;

        return $this;
    }

    public function getGain(): ?string
    {
        return $this->Gain;
    }

    public function setGain(string $Gain): self
    {
        $this->Gain = $Gain;

        return $this;
    }
}

src/Controller/VerifController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AuthenticationException;

class VerifController extends AbstractController
{


    #[Route('/verif', name: 'app_verif')]
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {


//        $user = $this->getDoctrine()->getRepository(User::class)->findAll([],['created_at' => 'desc']);

        if ($request->isMethod('POST')) {
        $code = $_POST['code'] ;
        $user = $doctrine->getRepository(User::class)->findBy(['code'=> $code]);

            // Verifie si le code existe
            if (!$user) {
                $error = "oui";
                return $this->render('verif/index.html.twig', [
                    'error' => $error
                ]);
            }

            return $this->render('verif/index.html.twig', [
                'user' => $user,
            ]);
        }
        return $this->render('verif/index.html.twig', [
        ]);


    }
    #[Route('/verif/{code}', name: 'app_verif2')]

    public function activateCode(ManagerRegistry $doctrine, EntityManagerInterface $em, UserRepository $userRepository, $code):Response
    {
//        $code = $_POST['code'] ;

        $user = $doctrine->getRepository(User::class)->findOneBy(['code'=> $code]);
        $user->setCodeActivated('Oui');
        $em->flush();

        return $this->render('verif/verif.html.twig', [
            'user' => $user,

        ]);
    }


}


//    #[Route('/verif/code', name: 'app_verif2')]
//    public function show( UserRepository $userRepository,string $code): Response
//    {
//
//        $code = $_GET['code'] ;
//        $user = $userRepository->findOneBy($code);
        // Verify user id
//        if (!$user) {
//            throw new AuthenticationException("Le code {$code} n'existe pas.");
//        }

//        $user = $this->$userRepository
//            ->findOneBy([
//                'code' => $_GET['code']
//            ]);


//        if ($product) {
//            throw $this->createNotFoundException(
//                "Pas d'utilisateur trouver pour ".$code
//            );
//        }

//        $user = $this->getDoctrine()->getRepository(User::class)->findAll([],['created_at' => 'desc']);


//        return $this->render('verif/index.html.twig', [
//            'code' => $code
//        ]);
//    }

templates/verif/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VerifController!{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('assets/styles/VerifStyle.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

{% endblock %}

{% block body %}
    <style>
        body {
            /*background: url("public/assets/img/background.jpg");*/

            background-color: #0F3947;
            color: #f6f6f6;

        }

        h5 {
            text-decoration-line: underline;
        }
    </style>

    <div class="s130 ">
        <form method="POST">
            <div class="inner-form">
                <div class="input-field first-wrap">
                    <div class="svg-wrapper">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                        </svg>
                    </div>
                    <label for="search">
                        <input id="search" type="text" placeholder="Entrez le code" name="code" maxlength="6"
                               minlength="6"/>
                    </label>
                </div>
                <div class="input-field second-wrap">
                    <button class="btn-search" type="submit">Rechercher</button>
                </div>
            </div>
            <span class="info">Le code fait 6 charactères</span>
            <div class="p-4 " style="text-align: center">
                {% if user is defined %}
                    {% for user in user %}
                        <h5 >Nom :</h5>
                        <p>
                            {{ user.name }}
                        </p>
                        <h5>Prénom :</h5>
                        <p>
                            {{ user.firstname }}
                        </p>
                        <h5>Adresse mail :</h5>
                        <p>
                            {{ user.mail }}
                        </p>
                        <h5>Date de création :</h5>
                        <p>
                            {{ user.creationTime|date("d/m/Y") }}
                        </p>
                        <h5>Code utilisé :</h5>
                        <p>
                            {{ user.codeActivated }}
                        </p>
                        <h5>Code :</h5>
                        <p>
                            {{ user.code }}
                        </p>
                        <h5>Gain :</h5>
                        <p>
                            {{ user.gain }}
                        </p>
                        {% if user.codeActivated == "Non" %}

                            <a href="{{ path('app_verif2', {code:  user.code  }) }}"
                               style="color: white; text-decoration: none">
                                <button class="btn btn-primary container" type="button">Utilisé le code</button>
                            </a>
                        {% else %}
                            <div class="alert alert-warning" role="alert">
                                Le code a déjà été utilisé.
                            </div>
                        {% endif %}
                    {% endfor %}
                {% elseif error is defined %}
                    <div class="alert alert-danger" role="alert">
                        Le code n'existe pas.
                    </div>
                {% endif %}
            </div>
        </form>
    </div>




    {# <div class="container"> #}
    {#    <p> #}

    {#        {{ user.code }} #}
    {#        {{ user.code }} #}

    {#    </p> #}
    {# </div> #}


{% endblock %}

templates/verif/verif.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VerifController!{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('assets/styles/VerifStyle.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

{% endblock %}

{% block body %}
    <style>
        body {
            /*background: url("public/assets/img/background.jpg");*/

            background-color: #0F3947;
            color: #f6f6f6;
            text-align: center;
            font-size: 4vh;
        }

        p h5 {
        }
    </style>


    <div class="container" style="padding: 100px;">
        {% if user.codeActivated == 'Oui' %}
            Le code {{ user.code }} a bien été utilisé.
        {% elseif user.codeActivated == 'Non' %}
            Le code {{ user.code }} a déjà été utilisé.
        {% endif %}
        <br>
        <a href="{{ path('app_verif') }}">
            <button class="btn btn-primary ">Revenir a la page d'accueil</button>
        </a>

    </div>




    {# <div class="container"> #}
    {#    <p> #}

    {#        {{ user.code }} #}
    {#        {{ user.code }} #}

    {#    </p> #}
    {# </div> #}


{% endblock %}